import AppKit
import SwiftUI

// MARK: - YouTubeAskPanelView

/// Collapsible, watch-scoped Ask Gemini panel. It only presents server-issued
/// suggestions; free-form input is intentionally not part of this surface.
struct YouTubeAskPanelView: View {
    let viewModel: YouTubeAskViewModel

    var body: some View {
        VStack(alignment: .leading, spacing: 12) {
            self.header

            Text(
                "Responses are generated by YouTube and may be inaccurate.",
                comment: "Disclosure shown in the YouTube Ask Gemini panel"
            )
            .font(.caption)
            .foregroundStyle(.secondary)
            .fixedSize(horizontal: false, vertical: true)

            if self.viewModel.isExpanded {
                Divider()
                    .opacity(0.4)

                self.expandedContent
            }
        }
        .padding(14)
        .compatGlass(in: .rect(cornerRadius: 14))
        .accessibilityElement(children: .contain)
        .accessibilityIdentifier(AccessibilityID.YouTubeContent.askPanel)
        .onChange(of: self.viewModel.accessibilityAnnouncementSequence) { _, _ in
            guard let announcement = self.viewModel.accessibilityAnnouncement else { return }
            self.postLiveRegionAnnouncement(self.accessibilityText(for: announcement))
        }
        .onChange(of: self.viewModel.presentationError) { _, error in
            guard let error else { return }
            self.postLiveRegionAnnouncement(self.errorText(for: error))
        }
    }

    private var header: some View {
        Button {
            self.viewModel.toggleExpanded()
        } label: {
            HStack(spacing: 9) {
                Image(systemName: "sparkles")
                    .font(.system(size: 14, weight: .semibold))
                    .foregroundStyle(.tint)

                Text("Ask Gemini", comment: "YouTube watch-page Ask Gemini panel title")
                    .font(.headline)
                    .foregroundStyle(.primary)

                Spacer(minLength: 8)

                Image(systemName: self.viewModel.isExpanded ? "chevron.up" : "chevron.down")
                    .font(.system(size: 11, weight: .semibold))
                    .foregroundStyle(.secondary)
            }
            .frame(maxWidth: .infinity, alignment: .leading)
            .contentShape(Rectangle())
        }
        .buttonStyle(.plain)
        .accessibilityLabel(
            self.viewModel.isExpanded
                ? String(localized: "Collapse Ask Gemini")
                : String(localized: "Expand Ask Gemini")
        )
        .accessibilityIdentifier(AccessibilityID.YouTubeContent.askToggle)
    }

    private var expandedContent: some View {
        VStack(alignment: .leading, spacing: 12) {
            if !self.viewModel.messages.isEmpty {
                self.transcript
            }

            if let error = self.viewModel.presentationError {
                self.errorStatus(error)
            } else if self.viewModel.activity != .idle {
                self.progressStatus
            }

            if !self.viewModel.suggestions.isEmpty, !self.viewModel.requiresNewChat {
                self.suggestions
            }

            if self.viewModel.canStartNewChat {
                Button {
                    self.viewModel.startNewChat()
                } label: {
                    Label(String(localized: "New Chat"), systemImage: "arrow.clockwise")
                        .font(.system(size: 12, weight: .semibold))
                        .frame(maxWidth: .infinity)
                        .padding(.vertical, 7)
                }
                .buttonStyle(.bordered)
                .disabled(self.viewModel.isBusy)
                .accessibilityIdentifier(AccessibilityID.YouTubeContent.askNewChat)
            }
        }
    }

    private var transcript: some View {
        ScrollViewReader { proxy in
            ScrollView(.vertical) {
                LazyVStack(alignment: .leading, spacing: 10) {
                    ForEach(self.viewModel.messages) { message in
                        self.messageView(message)
                            .id(message.id)
                    }
                }
                .frame(maxWidth: .infinity, alignment: .leading)
                .padding(.trailing, 4)
            }
            .frame(maxHeight: 240)
            .accessibilityIdentifier(AccessibilityID.YouTubeContent.askTranscript)
            .onChange(of: self.viewModel.messages.map(\.id)) { _, messageIDs in
                guard let lastID = messageIDs.last else { return }
                proxy.scrollTo(lastID, anchor: .bottom)
            }
        }
    }

    @ViewBuilder
    private func messageView(_ message: YouTubeAskMessage) -> some View {
        switch message.role {
        case .user:
            Text(verbatim: message.text)
                .font(.callout.weight(.medium))
                .foregroundStyle(.primary)
                .multilineTextAlignment(.leading)
                .padding(.horizontal, 10)
                .padding(.vertical, 8)
                .background(Color.accentColor.opacity(0.12), in: .rect(cornerRadius: 10))
                .frame(maxWidth: .infinity, alignment: .trailing)
                .accessibilityLabel(
                    String(
                        localized: "You asked: \(message.text)",
                        comment: "VoiceOver label for a user turn in the YouTube Ask Gemini transcript"
                    )
                )
        case .assistant:
            YouTubeAskMarkdownView(markdown: message.text)
                .foregroundStyle(.primary)
                .multilineTextAlignment(.leading)
                .fixedSize(horizontal: false, vertical: true)
                .frame(maxWidth: .infinity, alignment: .leading)
                .accessibilityElement(children: .ignore)
                .accessibilityLabel(
                    String(
                        localized: "YouTube response: \(YouTubeAskMarkdown.plainText(from: message.text))",
                        comment: "VoiceOver label for an assistant turn in the YouTube Ask Gemini transcript"
                    )
                )
        }
    }

    private var suggestions: some View {
        VStack(alignment: .leading, spacing: 8) {
            ForEach(Array(self.viewModel.suggestions.enumerated()), id: \.element.id) { index, suggestion in
                Button {
                    self.viewModel.selectSuggestion(id: suggestion.id)
                } label: {
                    Text(verbatim: suggestion.text)
                        .font(.system(size: 12, weight: .medium))
                        .foregroundStyle(.primary)
                        .multilineTextAlignment(.leading)
                        .fixedSize(horizontal: false, vertical: true)
                        .frame(maxWidth: .infinity, alignment: .leading)
                        .padding(.horizontal, 11)
                        .padding(.vertical, 9)
                        .background(.quaternary.opacity(0.55), in: .rect(cornerRadius: 10))
                        .contentShape(.rect(cornerRadius: 10))
                }
                .buttonStyle(.plain)
                .disabled(self.viewModel.isBusy)
                .accessibilityIdentifier(AccessibilityID.YouTubeContent.askSuggestion(index: index))
            }
        }
    }

    private var progressStatus: some View {
        HStack(spacing: 8) {
            ProgressView()
                .controlSize(.small)
            Text(self.activityText)
                .font(.caption)
                .foregroundStyle(.secondary)
        }
        .accessibilityElement(children: .combine)
        .accessibilityIdentifier(AccessibilityID.YouTubeContent.askStatus)
    }

    private func errorStatus(_ error: YouTubeAskPresentationError) -> some View {
        Label(self.errorText(for: error), systemImage: "exclamationmark.triangle")
            .font(.caption)
            .foregroundStyle(.secondary)
            .fixedSize(horizontal: false, vertical: true)
            .accessibilityIdentifier(AccessibilityID.YouTubeContent.askStatus)
    }

    private var activityText: String {
        switch self.viewModel.activity {
        case .idle:
            ""
        case .preparing:
            String(localized: "Preparing Ask Gemini…")
        case .sending:
            String(localized: "Sending…")
        }
    }

    private func errorText(for error: YouTubeAskPresentationError) -> String {
        switch error {
        case .authentication:
            String(localized: "Sign in again to use Ask Gemini.")
        case .rateLimited:
            String(localized: "Ask Gemini is temporarily rate limited. Try again later.")
        case .preparation:
            String(localized: "Ask Gemini couldn’t prepare this chat.")
        case .restartRequired:
            String(localized: "Start a new chat to continue.")
        }
    }

    private func accessibilityText(for announcement: YouTubeAskViewModel.AccessibilityAnnouncement) -> String {
        switch announcement {
        case .responseReady:
            String(localized: "Ask Gemini response ready")
        case .newChatReady:
            String(localized: "New Ask Gemini chat ready")
        }
    }

    private func postLiveRegionAnnouncement(_ message: String) {
        NSAccessibility.post(
            element: NSApplication.shared,
            notification: .announcementRequested,
            userInfo: [
                .announcement: message,
                .priority: NSAccessibilityPriorityLevel.medium.rawValue,
            ]
        )
    }
}

// MARK: - AccessibilityID.YouTubeContent

extension AccessibilityID.YouTubeContent {
    static let askPanel = "youtubeContent.askPanel"
    static let askToggle = "youtubeContent.askToggle"
    static let askTranscript = "youtubeContent.askTranscript"
    static let askNewChat = "youtubeContent.askNewChat"
    static let askStatus = "youtubeContent.askStatus"

    static func askSuggestion(index: Int) -> String {
        "youtubeContent.askSuggestion.\(index)"
    }
}
